openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        "200":
          description: ""
      tags:
        - App
info:
  title: サンプルAPI
  description: サンプルAPIの紹介
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  schemas: {}
